In [1]:
#first, I load in my dataset from the sql database and process it for ML use
import pymssql
import pandas as pd
import numpy as np
database = "group1"
table = "dbo.capstone_sql_table"
username = "group1user"
password  = "everythingIsAwesome!"
server = "database2108.database.windows.net"

conn = pymssql.connect(server,username, password,database)

cursor = conn.cursor()
query = 'select * from capstone_sql_table'
rawDF = pd.read_sql(query, conn)

In [3]:
no_giniDF = rawDF[rawDF['Gini index (World Bank estimate)'].isna()]
no_giniDF.head()

,year,country,"Stocks traded, total value (% of GDP)","Inflation, consumer prices (annual %)","Stocks traded, turnover ratio of domestic shares (%)",Tax revenue (% of GDP),GDP per capita (current US$),"Central government debt, total (% of GDP)",Gini index (World Bank estimate),Broad money (% of GDP),"Total reserves (includes gold, current US$)","International migrant stock, total",Income share held by highest 10%,Poverty headcount ratio at national poverty lines (% of population),"Life expectancy at birth, total (years)","Mortality rate, infant (per 1,000 live births)","Unemployment, total (% of total labor force) (modeled ILO estimate)",Exports of goods and services (% of GDP),timestamp
1,1998,DOM,None,4.83166558591895,None,11.4316696590021,2638.31327013425,None,None,25.1631175101779,5.07121243385005E8,None,None,None,68.925,34.8,6.42,34.3098842791,1635706359829
2,2005,LBN,4.19633381113584,None,18.7553016316551,15.1681037723611,4575.10745896031,None,None,229.447901132825,1.66179705714448E10,756784.0,None,None,76.865,12.1,8.27,36.6235387089593,1635714811299
3,2013,PYF,None,None,None,None,None,None,None,None,None,None,None,None,76.307,None,11.77,None,1635723266916
4,2006,LBN,9.12953044177348,None,24.6878668362811,15.0082855367349,4626.85300341662,None,None,241.43641489229,1.92388670613303E10,None,None,None,77.26,11.2,8.62,35.5896575059132,1635714816354
5,2014,PYF,None,None,None,None,None,None,None,None,None,None,None,None,76.546,None,11.92,None,1635723271928

In [4]:
no_giniDF.drop(columns=['timestamp','Poverty headcount ratio at national poverty lines (% of population)', 
                     'Life expectancy at birth, total (years)', 
                     'Mortality rate, infant (per 1,000 live births)', 'Unemployment, total (% of total labor force) (modeled ILO estimate)', 
                     'Income share held by highest 10%', 'Central government debt, total (% of GDP)', 
                     'International migrant stock, total', 'Stocks traded, turnover ratio of domestic shares (%)'], inplace=True)

C:\Users\Admin\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [5]:
no_giniDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5084 entries, 1 to 6726
Data columns (total 10 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   year                                         5084 non-null   object
 1   country                                      5084 non-null   object
 2   Stocks traded, total value (% of GDP)        1295 non-null   object
 3   Inflation, consumer prices (annual %)        3624 non-null   object
 4   Tax revenue (% of GDP)                       1897 non-null   object
 5   GDP per capita (current US$)                 4480 non-null   object
 6   Gini index (World Bank estimate)             0 non-null      object
 7   Broad money (% of GDP)                       3441 non-null   object
 8   Total reserves (includes gold, current US$)  3612 non-null   object
 9   Exports of goods and services (% of GDP)     3823 non-null   object
dtypes: object(10)
memory usage: 436.9+ KB

In [6]:
no_giniDF = no_giniDF[no_giniDF['Stocks traded, total value (% of GDP)'].notna()]
no_giniDF = no_giniDF[no_giniDF['Inflation, consumer prices (annual %)'].notna()]
no_giniDF = no_giniDF[no_giniDF['Tax revenue (% of GDP)'].notna()]
no_giniDF = no_giniDF[no_giniDF['GDP per capita (current US$)'].notna()]
no_giniDF = no_giniDF[no_giniDF['Broad money (% of GDP)'].notna()]
no_giniDF = no_giniDF[no_giniDF['Total reserves (includes gold, current US$)'].notna()]
no_giniDF = no_giniDF[no_giniDF['Exports of goods and services (% of GDP)'].notna()]
no_giniDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 599 entries, 182 to 6674
Data columns (total 10 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   year                                         599 non-null    object
 1   country                                      599 non-null    object
 2   Stocks traded, total value (% of GDP)        599 non-null    object
 3   Inflation, consumer prices (annual %)        599 non-null    object
 4   Tax revenue (% of GDP)                       599 non-null    object
 5   GDP per capita (current US$)                 599 non-null    object
 6   Gini index (World Bank estimate)             0 non-null      object
 7   Broad money (% of GDP)                       599 non-null    object
 8   Total reserves (includes gold, current US$)  599 non-null    object
 9   Exports of goods and services (% of GDP)     599 non-null    object
dtypes: object(10)
memory usage: 51.5+ KB

In [7]:
no_giniDF.head()

,year,country,"Stocks traded, total value (% of GDP)","Inflation, consumer prices (annual %)",Tax revenue (% of GDP),GDP per capita (current US$),Gini index (World Bank estimate),Broad money (% of GDP),"Total reserves (includes gold, current US$)",Exports of goods and services (% of GDP)
182,2011,ARE,4.27882049019235,0.877346595685083,0.321413865338428,39194.672239975,None,63.1430144406715,3.72693184225758E10,90.0765712005007
183,2012,ARE,4.79238660004768,0.662268900269082,0.36378633951547,40976.4907464015,None,61.7624396300313,4.70351504309523E10,100.246495561481
185,2014,ARE,35.7358495939018,2.34626865671643,0.355723150336942,43751.8056478669,None,76.0156728611077,7.84243816650826E10,99.5608302752882
186,2015,ARE,16.0828544247448,4.06996608361598,0.0577340241915802,38663.4005026605,None,90.2350197794946,9.39291341964176E10,100.870480235332
187,2016,ARE,13.8547300872909,1.61748808904192,0.0434947005242334,38141.8671313451,None,93.4571492196747,8.53908327463078E10,101.003013922614

In [8]:
c_y_DF = no_giniDF.drop(columns=['Gini index (World Bank estimate)'])
modelDF = c_y_DF.drop(columns=['country','year'])
# used the code up to this point to get these two dataframes into Power BI
# I then used the modelDF and the pickle file to create a predicted outcome column in Power Query
# I then merged it with the c_y_DF in Power BI to make visualizations with both the predicted outcomes and the country/year
# The rest of this file is how I would have created the outcomes column in Python rather than Power Query

In [9]:
import pickle
filename = 'gini_index_final_model_with_imputation.pkl'

In [10]:
loaded_model = pickle.load(open(filename, 'rb'))
predicted_gini = loaded_model.predict(modelDF)
print(predicted_gini)

[28.21327373 28.73569254 30.51115192 31.36055549 31.48449668 29.6698569
 29.96615754 36.90170956 36.87616063 44.70478845 36.09725496 38.08962425
 36.05252187 35.73584409 36.33098183 36.12360306 36.58602813 35.34007004
 34.6644679  36.01878887 40.30312917 35.16364486 39.33885607 39.35450607
 41.66762083 41.45402698 42.54112702 40.84406369 32.11647671 44.24337524
 44.26449579 44.2439504  43.68493361 45.25994083 46.34552952 45.6060048
 46.14127591 40.87640448 35.37080172 36.10130784 35.32398296 35.46231893
 35.76238857 35.71115175 35.87522377 35.38808214 35.52279891 35.20326532
 42.67889429 38.85419095 37.69898897 35.94688016 41.70032917 44.68149373
 42.70803972 36.32537976 35.35411798 36.17675063 36.02622385 36.15294121
 36.26352917 44.3856229  44.66819921 41.74478401 42.80213194 44.17746702
 44.44434298 44.2222323  42.88468012 45.05498615 44.89751647 51.48766643
 43.17608063 45.97427845 48.50423988 50.54977363 46.54056482 43.83868266
 44.34515389 46.78894365 42.43343496 41.60655389 42.48221504 42.25500552
 41.50849057 41.31495135 41.65095956 41.14763643 43.27490726 43.46024956
 45.04192762 51.74820583 52.41281857 52.02706893 51.09327702 51.39353238
 51.88711381 47.98347147 44.53215083 40.96510408 41.00381196 44.53648226
 39.22532991 40.11152429 50.59766909 47.99004647 46.44028603 46.85413607
 43.56641313 45.83726583 45.96555976 47.20897381 45.59436333 41.15949904
 42.17007273 46.42198317 37.89095734 42.32638425 40.83575444 43.4882923
 45.6742456  46.67823067 47.22876294 47.25764615 47.34647603 40.66999607
 46.59316992 38.71648599 38.83539345 39.197315   39.06218821 39.1499825
 39.06727933 39.26925226 39.17773488 39.38450052 39.21010274 38.76287952
 38.35247095 38.018655   38.54217476 38.05241258 38.21771583 38.4158869
 38.09620048 37.50772373 37.5629149  37.74283811 38.63515883 37.32005423
 38.03828921 44.30749674 43.87474222 44.08499044 43.43835389 43.61519722
 43.76973437 44.3352046  44.35798853 42.00596282 43.25713544 42.82828782
 41.02216506 39.70987587 40.92710583 41.45441833 38.56636141 38.33211647
 46.6102398  47.39111611 39.91365528 39.32650694 38.84101599 38.92307448
 39.70247472 44.73483472 45.32568631 45.76762496 51.18052363 46.27846266
 30.64776405 30.37007548 30.51334405 30.71460821 30.73295762 38.06034147
 39.28089694 37.4261019  37.90241136 36.62140893 36.80353468 37.2418577
 37.92321989 36.70314774 36.06437731 35.66819635 36.50965381 33.91321933
 32.90225151 31.24124187 31.23939948 31.18413603 31.28802413 31.05795183
 32.06018115 31.93130377 31.8221202  32.04453472 32.0361052  31.67764758
 31.4165802  31.85929418 31.37762044 31.56060361 31.56295563 31.906115
 34.5153121  31.34762421 35.40864823 31.20730623 31.66821429 31.63492929
 31.07456405 31.4007608  31.46695596 31.46310287 31.46920037 31.56533834
 35.47801024 39.21507071 35.02247095 43.56269389 37.66812345 36.60779393
 40.36236615 36.63200968 37.81010548 42.94748345 48.14101933 43.57770873
 36.54613615 36.4807985  34.6205831  39.63743599 39.89146313 39.70517933
 39.68982139 39.88142631 39.55457599 32.61887714 32.61490845 32.81344857
 32.40858524 31.65636492 53.68323639 51.63451353 51.02669635 53.07365714
 52.75007869 50.76674179 35.18846024 38.40708468 43.29545782 37.1804121
 37.45018194 34.42383179 32.01333004 31.18687294 50.57531516 49.49864881
 45.97789643 45.15275917 43.25232599 36.34477381 36.22928869 36.74876946
 31.10903516 35.64826351 32.00323341 26.61818925 27.36653282 27.27199079
 26.77521901 26.06855718 33.83823389 33.83337482 32.99943798 50.67169813
 38.00383726 37.68432976 37.59461952 42.24622504 41.58289853 40.98731455
 38.95783119 41.81883538 39.94128236 41.37079952 32.4728119  32.24899671
 31.15971171 35.82062939 37.50312891 38.11899563 34.13164917 33.34273079
 26.82832131 27.43904111 27.09876552 26.94309863 26.6867571  26.48827234
 26.9904514  26.58240619 29.03234401 42.04941425 42.80835528 41.84210605
 39.4641325  39.52939393 39.62845702 39.56275849 36.41239683 36.25213091
 37.09888937 36.34761655 38.02697917 40.07126837 36.11319528 35.85943175
 36.16003317 36.27699353 37.0728506  40.71802091 27.16252012 26.31619323
 28.58450905 35.80121659 34.37988202 34.64059599 33.71385726 34.71464623
 35.45413817 32.83345575 34.80498151 35.49747758 34.48788861 36.95481073
 36.89622    36.50111458 36.38994609 36.93019075 36.37856704 36.80475671
 37.38449881 36.74360016 35.02844623 37.12533766 36.69969505 36.46336024
 36.72247802 37.04767992 36.34629778 36.6231729  37.43807964 37.89772536
 43.1281319  43.6240248  45.63426123 47.08637599 56.1063925  56.63966833
 53.27814817 53.86780603 56.36400702 55.72783905 54.81635512 44.05584135
 43.91485425 39.4690771  39.25281687 38.72107306 39.57369278 40.45108139
 38.71965413 39.58111881 40.12960762 38.67874837 38.88195045 37.93586617
 37.60109303 38.44677067 38.30952135 38.32026798 41.49261036 41.46418421
 42.48333627 46.77699147 40.70174512 39.76745716 39.56874133 36.97625906
 44.4067956  44.22779111 47.97033706 50.05076595 49.09966575 48.56673077
 45.46569083 43.10779222 42.77739095 41.02202071 45.36834025 39.09118058
 41.56897325 40.90272881 42.10081083 41.60214452 40.52597683 35.49954218
 35.68983825 32.54883536 33.28772675 32.40282953 32.63231167 31.73603215
 32.05994643 32.26027571 32.56817579 33.44357226 33.02716802 32.64048913
 35.00080254 40.87105291 38.23284466 36.73099246 36.58226791 36.73963907
 36.69889291 36.71423399 36.80217694 35.9447245  37.02958877 36.01217768
 36.95764944 36.88517266 36.92284401 36.98403159 36.95931933 36.70483552
 46.83272754 50.94981496 51.92244841 51.86878389 46.72614817 46.84604881
 44.70834611 43.2902021  44.33549468 40.16493751 38.70571452 36.78318226
 35.58103516 43.90571627 44.21431056 44.12796341 39.25571389 44.3422396
 43.40159298 43.61930877 40.79785608 42.24407944 37.2390276  41.25425718
 41.29357179 42.91232091 43.55511448 36.00059417 34.70215734 52.70462524
 51.35585274 48.45438249 44.26697177 43.91894563 43.44868996 47.28938505
 43.58113865 43.20711429 30.07489881 32.7387148  33.4752079  33.55568976
 34.14143334 33.95956429 35.06646492 36.73511214 34.18819163 34.53093164
 34.19993938 33.72742667 33.71819067 33.74655333 33.53322206 33.43233135
 33.33325706 33.36122067 33.49614635 32.70066425 32.95458219 53.07290448
 51.99934043 50.46885845 48.91009097 51.00932294 47.97168978 47.24392045
 39.96594883 40.59704044 39.54867534 39.23977167 32.67322111 40.30064268
 40.34139756 42.8794282  42.61630237 42.5435951  38.72130536 42.4766394
 42.44800817 42.7319752  34.81912224 35.20340462 49.90452032 50.67754996
 50.54231921 49.00893937 46.5929381  44.13856233 45.25433401 39.67440813
 39.77545167 40.2859906  39.46492996 40.14949861 43.979909   46.57995214
 52.35896556 39.2539581  41.05004325 37.0328729  37.26863516 38.52892706
 37.83313774 37.86362679 34.13447607 33.87361155 31.55062572 27.62193536
 27.12048024 26.98956972 25.54409437 25.04560349 25.31998079 25.1787498
 25.08199103 25.93018627 26.12966393 53.82519022 53.30428904 54.34763048
 56.36950464 54.79433476 50.54664074 51.43133488 55.9543829  56.98654207
 54.89248869 54.36002524 55.66472869 54.31002081 52.25800502 49.11194452
 45.60408849 48.92058155 48.67679738 48.91337952 50.38223869 50.12005381
 49.39826714 49.71862905 50.29000155 44.37862738 46.22385242 43.89904524
 44.21441607 45.40909302 47.19320635 44.6980594  41.41810179]

In [11]:
predictions = pd.DataFrame(predicted_gini,columns=['predicted_gini'])
predictions.head()

   predicted_gini
0       28.213274
1       28.735693
2       30.511152
3       31.360555
4       31.484497

In [12]:

modelDF.reset_index(inplace=True)

modelDF.head()

,index,"Stocks traded, total value (% of GDP)","Inflation, consumer prices (annual %)",Tax revenue (% of GDP),GDP per capita (current US$),Broad money (% of GDP),"Total reserves (includes gold, current US$)",Exports of goods and services (% of GDP)
0,182,4.27882049019235,0.877346595685083,0.321413865338428,39194.672239975,63.1430144406715,3.72693184225758E10,90.0765712005007
1,183,4.79238660004768,0.662268900269082,0.36378633951547,40976.4907464015,61.7624396300313,4.70351504309523E10,100.246495561481
2,185,35.7358495939018,2.34626865671643,0.355723150336942,43751.8056478669,76.0156728611077,7.84243816650826E10,99.5608302752882
3,186,16.0828544247448,4.06996608361598,0.0577340241915802,38663.4005026605,90.2350197794946,9.39291341964176E10,100.870480235332
4,187,13.8547300872909,1.61748808904192,0.0434947005242334,38141.8671313451,93.4571492196747,8.53908327463078E10,101.003013922614

In [13]:
modelDF.drop(columns=['index'],inplace=True)
modelDF.head()

,"Stocks traded, total value (% of GDP)","Inflation, consumer prices (annual %)",Tax revenue (% of GDP),GDP per capita (current US$),Broad money (% of GDP),"Total reserves (includes gold, current US$)",Exports of goods and services (% of GDP)
0,4.27882049019235,0.877346595685083,0.321413865338428,39194.672239975,63.1430144406715,3.72693184225758E10,90.0765712005007
1,4.79238660004768,0.662268900269082,0.36378633951547,40976.4907464015,61.7624396300313,4.70351504309523E10,100.246495561481
2,35.7358495939018,2.34626865671643,0.355723150336942,43751.8056478669,76.0156728611077,7.84243816650826E10,99.5608302752882
3,16.0828544247448,4.06996608361598,0.0577340241915802,38663.4005026605,90.2350197794946,9.39291341964176E10,100.870480235332
4,13.8547300872909,1.61748808904192,0.0434947005242334,38141.8671313451,93.4571492196747,8.53908327463078E10,101.003013922614

In [14]:
modelDF['Gini ML Model Predictions']=predictions

In [17]:
modelDF.head(20)
modelDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 599 entries, 0 to 598
Data columns (total 8 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Stocks traded, total value (% of GDP)        599 non-null    object
 1   Inflation, consumer prices (annual %)        599 non-null    object
 2   Tax revenue (% of GDP)                       599 non-null    object
 3   GDP per capita (current US$)                 599 non-null    object
 4   Broad money (% of GDP)                       599 non-null    object
 5   Total reserves (includes gold, current US$)  599 non-null    object
 6   Exports of goods and services (% of GDP)     599 non-null    object
 7   Gini ML Model Predictions                    599 non-null    float64
dtypes: float64(1), object(7)
memory usage: 37.6+ KB

In [23]:
c_y_DF.reset_index(inplace=True)
c_y_DF.drop(columns=['index'],inplace=True)
c_y_DF['Gini ML Model Predictions'] = predictions
c_y_DF['Stocks traded, total value (% of GDP)'] = c_y_DF['Stocks traded, total value (% of GDP)'].astype(float)
c_y_DF['Inflation, consumer prices (annual %)'] = c_y_DF['Inflation, consumer prices (annual %)'].astype(float)
c_y_DF['Tax revenue (% of GDP)'] = c_y_DF['Tax revenue (% of GDP)'].astype(float)
c_y_DF['GDP per capita (current US$)'] = c_y_DF['GDP per capita (current US$)'].astype(float)
c_y_DF['Broad money (% of GDP)'] = c_y_DF['Broad money (% of GDP)'].astype(float)
c_y_DF['Total reserves (includes gold, current US$)'] = c_y_DF['Total reserves (includes gold, current US$)'].astype(float)
c_y_DF['Exports of goods and services (% of GDP)'] = c_y_DF['Exports of goods and services (% of GDP)'].astype(float)
c_y_DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 599 entries, 0 to 598
Data columns (total 10 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   year                                         599 non-null    object
 1   country                                      599 non-null    object
 2   Stocks traded, total value (% of GDP)        599 non-null    float64
 3   Inflation, consumer prices (annual %)        599 non-null    float64
 4   Tax revenue (% of GDP)                       599 non-null    float64
 5   GDP per capita (current US$)                 599 non-null    float64
 6   Broad money (% of GDP)                       599 non-null    float64
 7   Total reserves (includes gold, current US$)  599 non-null    float64
 8   Exports of goods and services (% of GDP)     599 non-null    float64
 9   Gini ML Model Predictions                    599 non-null    float64
dtypes: float64(8), object(2)
memory usage: 46.9+ KB